spring:
  application:
    name: cast

  profiles:
    active: dev

#logging:
 # level:
  #  org.springframework.jdbc.datasource: DEBUG
   # org.hibernate.SQL: DEBUG

# Configuração padrão (dev)
---
spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:postgresql://172.31.61.65:5433/banco_cast
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8520

# Configuração para testes (H2 em memória)
---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect

# Configuração para produção
---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://prod-server:5432/banco_cast}
    username: ${SPRING_DATASOURCE_USERNAME:cast_user}
    password: ${SPRING_DATASOURCE_PASSWORD:cast_password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8520


# Configuração para rodar dentro do Docker
---
spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://postgres:5432/banco_cast
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8520
